### ISSUE TITLE
ember-cli-css-preprocess with precss

### ISSUE THREAD

**Issue by lcpriest** [n1ru4l/ember-cli-css-preprocess#6]
Hi. I'm currently having an issue with precss and at-rules. Using the new parser syntax, I had hoped this would be solved as postcss can handle at-rules.

The error is really generic, I apologise.

```
Build error

/app/styles/app.scss (in my-app/tmp/style_processor-input_base_path-1nhVJQ2W.tmp/0)

Error
Error
    at my-app/node_modules/ember-cli-css-preprocess/style-processor.js:188:35
    at lib$es6$promise$$internal$$tryCatch (my-app/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (my-app/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (my-app/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$$internal$$publishRejection (my-app/node_modules/es6-promise/dist/es6-promise.js:264:7)
    at lib$es6$promise$asap$$flush (my-app/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
```

Recreation steps:

1 - `ember new test-app`
2 - 
```
ember install ember-cli-css-preprocess
npm install precss --save-dev
npm install postcss-scss --save-dev
```
3 -

`ember-cli-build.js`
```
...
styleProcessorOptions: {
  extension: 'scss',
  processors: [{
    type: 'postcss',
    parser: require('postcss-scss'),
    plugins: [
      {
        module: require('precss'),
        options: {},
      }
    ],
  }],
},
...
```
4 - 
`base.scss`
```
html {
  background: red;
}
```
5 - 
`app.scss`
```
@import 'base.scss'
```

6 - `ember server`

**Comment by lcpriest** [comment]
I also have a test repo with this on if that's easier.

**Comment by n1ru4l** [comment]
I will take a look at it this evening!

**Comment by n1ru4l** [comment]
Fixed in 248e5f4ffda224684877fe9777562c455c2fa8b8

Also imports in precss do not work this way, take a look at
https://github.com/jonathantneal/precss

Would like to hear feedback from you!

**Comment by lcpriest** [comment]
Ah sorry. Was it a bug or my code?

**Comment by lcpriest** [comment]
I'll test it out tonight and leave some comments!

**Comment by lcpriest** [comment]
I think it's still occurring:
https://github.com/lcpriest/ember-cli-css-preprocess-demo

**Comment by n1ru4l** [comment]
Please rename your ``base.scss`` to ``_base.css`` and let me know if the issue still occurs.

**Comment by lcpriest** [comment]
I think I'll try the other plugin also, but even renaming the file didn't work for me.

**Comment by lcpriest** [comment]
The demo app above demonstrates the error:
```
/app/styles/app.scss (in ~/my-app/tmp/style_processor-input_base_path-ASZAQfib.tmp/0)

filename is not defined
```

**Comment by n1ru4l** [comment]
I just fixed this issue in a48f77c20273225b4fe432fb349e20913f39bc8a

It should now work the way i described it, filename was a undefined variable :hankey:

**Comment by lcpriest** [comment]
Yup! It works on the demo app I produced. I'm still having an issue with my own, but I think it's just a config issue on my end. Thanks!
